### ISSUE TITLE
How can I set the Timezone ?

### ISSUE THREAD

**Issue by F72M** [jr0w3/docker-glpi#2]
My GLPI is 2hrs late from what I would like. For example if it's 11:00 am my GLPI will show 9:00pm.
My linux server on the other side will show 11:00 pm.

How can I configure the glpi timezone please ?
I saw the advice to use "php bin/console database:enable_timezones" and tried it in docker exec but it doesn't work.

Thanks a lot.

**Comment by jr0w3** [comment]
Fixed in https://github.com/jr0w3/docker-glpi/commit/bf60658a472b11ef5f25c1e6896377a517250a91
